# Site settings
title: Yiyuan Jia
email: yiyuan1840@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hello, Welcome to my website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.transgalaxy.us" # the base hostname & protocol for your site
twitter_username: yiyuan1840  
github_username:  yiyuan1840

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
